services:
  - type: web
    name: auction-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 